title: My test blog
author: Rachel Normand
email: racheljnewstead@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This will be awesome.

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

